export const users = [
  {
    id: 1,
    fullName: 'Jeff Chapman',
    image: 'https://randomuser.me/api/portraits/thumb/men/99.jpg',
    companyName: "Blanda-O'Keefe",
    jobTitle: 'Help Desk Operator',
  },
  {
    id: 2,
    fullName: 'Nicky Hunter',
    image: 'https://randomuser.me/api/portraits/thumb/women/91.jpg',
    companyName: 'Aufderhar-Cronin',
    jobTitle: 'Senior Cost Accountant',
  },
  {
    id: 3,
    fullName: 'Ritthy Gilbert',
    image: 'https://randomuser.me/api/portraits/thumb/men/0.jpg',
    companyName: 'Lindgren LLC',
    jobTitle: 'Clinical Specialist',
  },
  {
    id: 4,
    fullName: 'Allan Washington',
    image: 'https://randomuser.me/api/portraits/thumb/men/13.jpg',
    companyName: 'Wolff and Sons',
    jobTitle: 'Paralegal',
  },
  {
    id: 5,
    fullName: 'Lina Hubert',
    image: 'https://randomuser.me/api/portraits/thumb/women/53.jpg',
    companyName: 'Adams Inc',
    jobTitle: 'Web Developer',
  },
  {
    id: 6,
    fullName: 'Eloïse Roussel',
    image: 'https://randomuser.me/api/portraits/thumb/women/1.jpg',
    companyName: "D'Amore and Sons",
    jobTitle: 'Civil Engineer',
  },
  {
    id: 7,
    fullName: 'Nicole Hansen',
    image: 'https://randomuser.me/api/portraits/thumb/women/45.jpg',
    companyName: 'Schimmel, Wilderman',
    jobTitle: 'Sales Associate',
  },
  {
    id: 8,
    fullName: 'Jenny Nelson',
    image: 'https://randomuser.me/api/portraits/thumb/women/52.jpg',
    companyName: 'Corkery, Reichert',
    jobTitle: 'Clinical Specialist',
  },
  {
    id: 9,
    fullName: 'Jimmy Steward',
    image: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
    companyName: 'Gorczany Group',
    jobTitle: 'Community Outreach Specialist',
  },
  {
    id: 10,
    fullName: 'Ugo Faure',
    image: 'https://randomuser.me/api/portraits/thumb/men/74.jpg',
    companyName: 'Bins Group',
    jobTitle: 'Senior Sales Associate',
  },
]
